### PR TITLE
fix generate_biom_and_metadata_release

### PR DESCRIPTION
**Pull request by antgonza**
found a small bug during today's deploy

### CODE REVIEW

**Comment by ElDeveloper** [comment]
Looks good, but worth adding a test?

**Comment by antgonza** [comment]
What kind of test? The problem was that the code was using bdir_len vs os.path internal functions so if the system configuration was `path` vs. `path/` the files will not be found.

**Comment by ElDeveloper** [comment]
A regression test would catch that right? Changing the config.

**Comment by ElDeveloper** [comment]
👍 thanks @antgonza!!

**Pull request merged**
