### PR TITLE
Potentially resolves the performance issues

### LINKED ISSUE #887: Performance improvements retrieving files
- [x] Improve speed of opening the main meta-analysis page, this is still slow compared to opening a job. My guess a lot of object creation.
- [ ] Improve either how get_accessible_filepath_ids retrieves all ids or like in this case change it that so it doesn't retrieve all fp ids but just checking if fileA can be accessed by UserB

### PR DESCRIPTION
**Pull request by wasade**
Fixes #887 

~~**DO NOT MERGE**~~, we are testing on a larger set of studies and analyses.

### CODE REVIEW

**Comment by wasade** [comment]
Note, this performance issue was due to a local build issue on @antgonza's system. This has been resolved. However, this PR is still relevant as these properties and methods do not need to care about order (and they should not anyway as the order in the current structures in master is not assured)

**Comment by antgonza** [comment]
:+1:

**Comment by squirrelo** [comment]
:+1: if testing is done

**Comment by adamrp** [comment]
:+1:

**Comment by adamrp** [comment]
@wasade can this be merged now? Just asking because the initial comment still says "DO NOT MERGE"

**Comment by wasade** [comment]
It has now been crossed out :)

**Comment by josenavas** [comment]
@adamrp @squirrelo You've been reviewing this PR, can you merge if it looks ok to you?

**Pull request merged**
