### PR TITLE
REL: Final fixes for alpha-0.1

### PR DESCRIPTION
**Pull request by ElDeveloper**
Ready for merge.

cc @josenavas, @antgonza, @squirrelo , @wasade, @adamrp

### CODE REVIEW

**Comment by wasade** [comment]
pulling down in a new env

**Comment by wasade** [comment]
In a new env, just python2.7, I get the following:

```python
(qiita_0.1)22:23:57 qiita@alpha-0.1$ pip install -e .
Obtaining file:///Users/mcdonadt/ResearchWork/software/qiita
  Running setup.py egg_info for package from file:///Users/mcdonadt/ResearchWork/software/qiita

    warning: no previously-included files matching '*.pyo' found anywhere in distribution
    warning: no previously-included files matching '.git' found anywhere in distribution
    warning: no previously-included files matching '*~' found anywhere in distribution
Downloading/unpacking psycopg2 (from qiita-spots==0.1.0)
  Downloading psycopg2-2.6.tar.gz (367kB): 367kB downloaded
  Running setup.py egg_info for package psycopg2

    Error: pg_config executable not found.

    Please add the directory containing pg_config to the PATH
    or specify the full executable path with the option:

        python setup.py build_ext --pg-config /path/to/pg_config build ...

    or with the pg_config option in 'setup.cfg'.
    Complete output from command python setup.py egg_info:
    running egg_info

creating pip-egg-info/psycopg2.egg-info

writing pip-egg-info/psycopg2.egg-info/PKG-INFO

writing top-level names to pip-egg-info/psycopg2.egg-info/top_level.txt

writing dependency_links to pip-egg-info/psycopg2.egg-info/dependency_links.txt

writing manifest file 'pip-egg-info/psycopg2.egg-info/SOURCES.txt'

warning: manifest_maker: standard file '-c' not found



Error: pg_config executable not found.



Please add the directory containing pg_config to the PATH

or specify the full executable path with the option:



    python setup.py build_ext --pg-config /path/to/pg_config build ...



or with the pg_config option in 'setup.cfg'.

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /Users/mcdonadt/.virtualenvs/qiita_0.1/build/psycopg2
Storing complete log in /Users/mcdonadt/.pip/pip.log
```

The same happens if I try to install psycopg2 by itself through pip, has anyone else encountered this?

**Comment by wasade** [comment]
Cheated around it, `pg_config` is in `/Applications/Postgres.app/Contents/MacOS/bin` if you have `Postgres.app`. Install is proceeding.

**Comment by ElDeveloper** [comment]
@wasade, weird, for me it is in: export PATH=$PATH:/Applications/Postgres.app/Contents/Versions/9.3/bin/
 as i noted in my latest updates to INSTALL.md https://github.com/biocore/qiita/blob/master/INSTALL.md

**Comment by josenavas** [comment]
Code looks good to me. I don't have a clean environment as clean as the one that @wasade is trying to install, so if it works for him, :+1:

**Comment by wasade** [comment]
Weird... dunno. I'm blocking now on pandas, which has been installing w/o message for 10 mins. Falling back to doing what's described in the install doc.

**Comment by wasade** [comment]
@josenavas, I just did `mkvirtualenv foo`

@ElDeveloper, my system is flat out not compiling packages. It's been working for a few minutes on the very first actual compile in numpy. I recently bumped this laptop to 10.10, and apparently xcode is just flat out broken. I need to update it before proceeding.

**Comment by ElDeveloper** [comment]
BTW if you truly want to test this, these are the commands that you should run (make sure you have pg_config in your PATH, see INSTALL.md):

```bash
mkvirtualenv qiita-rc
pip install numpy
pip install https://github.com/biocore/mustached-octo-ironman/archive/master.zip --no-deps
python setup.py sdist
cp dist/qiita-spots-0.1.0.tar.gz ~/
cd
tar -xzvf qiita-spots-0.1.0.tar.gz
cd qiita-spots-0.1.0
pip install .
```

This is how I was founding all the problems I've fixed so far.

**Comment by ElDeveloper** [comment]
@biocore/qiita-admin It would be great if before merging this PR a couple of you can install as I mentioned above and make sure everything is working just fine. If you follow those steps and then follow from [INSTALL.md](https://github.com/biocore/qiita/blob/master/INSTALL.md#qiita-configuration) this should be representative of doing `pip install qiita-spots`.

**Comment by josenavas** [comment]
Ok... guys I cannot try this. I just broke my entire installation... This is the error that I'm receiving:
```
qiita webserver start
python(28624,0x7fff76dc4300) malloc: *** error for object 0x10eb2a6e0: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6
```
but this is even happening on my installation. I had an issue with zeromq and I had to re-install it. I think I broke my system... I'm to tired to try to fix it now, so will do tomorrow. Hopefully somebody else can try this w/o a problem!

**Comment by ElDeveloper** [comment]
Thanks @josenavas! I'm confident this should be the final changeset
before uploading to pypi, however I really would like to have at least
1-2 more people verify the install.

**Comment by antgonza** [comment]
I just tested in an empty installation and got this error:
```
 Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/antoniog/.virtualenvs/qiita-test/build/h5py/setup.py", line 140, in <module>
    cmdclass = CMDCLASS,
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/Users/antoniog/.virtualenvs/qiita-test/lib/python2.7/site-packages/setuptools/command/install.py", line 59, in run
    return orig.install.run(self)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/install.py", line 563, in run
    self.run_command('build')
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/build.py", line 127, in run
    self.run_command(cmd_name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup_build.py", line 140, in run
    from Cython.Build import cythonize
ImportError: No module named Cython.Build
```

I ran:
```
pip install numpy
pip install https://github.com/biocore/mustached-octo-ironman/archive/master.zip --no-deps
pip install -e .
```

I think the problem is that I have hdf5 and the qiime build is not actually pulling the right Cython.

**Comment by adamrp** [comment]
I'll give it a try in about 15 minutes.

**Comment by wasade** [comment]
My installs are happening, now that xcode is resolved however I just received the same error as @antgonza. Investigating

@josenavas, does that happen if you just start the interpreter? If not, recommend isolating, eg:

```python
> import tornado  # if this works then...
> import pyzmq # if this works then...
> import h5py # if this works then...
> import numpy # etc
```

If you cannot get into the interpreter, take a look at what is linked to the python executable and see if they make sense:

```bash
$ otool -L `which python`
```

**Comment by wasade** [comment]
@antgonza, installing cython out of band seemed to work. Can you try: `pip install cython`, and then  `pip install qiita-spots`? 

@ElDeveloper, it may be the case that we should either recommend installing `cython` prior like `numpy`, or that we add it explicitly to the deps. I'm having much more success on the install though it is still in progress

**Comment by wasade** [comment]
I'm now hitting linker issues as well:

```python
$ ./qiita_env start_cluster qiita_general && sleep 5
Traceback (most recent call last):
  File "./qiita_env", line 15, in <module>
    from qiita_db.environment_manager import (
  File "/Users/mcdonadt/rs/qiita/qiita_db/environment_manager.py", line 9, in <module>
    from qiita_db.ontology import Ontology
  File "/Users/mcdonadt/rs/qiita/qiita_db/ontology.py", line 29, in <module>
    from .base import QiitaObject
  File "/Users/mcdonadt/rs/qiita/qiita_db/base.py", line 30, in <module>
    from .sql_connection import SQLConnectionHandler
  File "/Users/mcdonadt/rs/qiita/qiita_db/sql_connection.py", line 85, in <module>
    from psycopg2 import (connect, ProgrammingError, Error as PostgresError,
  File "/Users/mcdonadt/.virtualenvs/qiita_0.1/lib/python2.7/site-packages/psycopg2/__init__.py", line 50, in <module>
    from psycopg2._psycopg import BINARY, NUMBER, STRING, DATETIME, ROWID
ImportError: dlopen(/Users/mcdonadt/.virtualenvs/qiita_0.1/lib/python2.7/site-packages/psycopg2/_psycopg.so, 2): Library not loaded: @loader_path/../lib/libssl.1.0.0.dylib
  Referenced from: /Users/mcdonadt/.virtualenvs/qiita_0.1/lib/python2.7/site-packages/psycopg2/_psycopg.so
  Reason: image not found
```

Which can be repeated with:

```python
>>> import psycopg2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mcdonadt/.virtualenvs/qiita_0.1/lib/python2.7/site-packages/psycopg2/__init__.py", line 50, in <module>
    from psycopg2._psycopg import BINARY, NUMBER, STRING, DATETIME, ROWID
ImportError: dlopen(/Users/mcdonadt/.virtualenvs/qiita_0.1/lib/python2.7/site-packages/psycopg2/_psycopg.so, 2): Library not loaded: @loader_path/../lib/libssl.1.0.0.dylib
  Referenced from: /Users/mcdonadt/.virtualenvs/qiita_0.1/lib/python2.7/site-packages/psycopg2/_psycopg.so
  Reason: image not found
```

**Comment by antgonza** [comment]
@wasade that worked but now getting the no Fortran error. What about adding to the installation tutorial that Mac users should download dmgs from:
http://sourceforge.net/projects/numpy/files/NumPy/
https://github.com/matplotlib/matplotlib/downloads
http://sourceforge.net/projects/scipy/files/scipy/

**Comment by squirrelo** [comment]
I have everything instaling nicely on my end, Had to use
```
ARCHFLAGS=-Wno-error=unused-command-line-argument-hard-error-in-future pip install .
```
Since I'm on OSX 10.10

**Comment by wasade** [comment]
@antgonza, haven't had to do .dmgs for a long time. Those specific packages install for me w/o issue, as does psycopg2. @squirrelo, testing your suggestion right now

**Comment by wasade** [comment]
@squirrelo, no go. Same library error.

It is possible I have out of sync system libraries due to the xcode update. 

@ElDeveloper, I'm going to get a VM and test in there.

**Comment by ElDeveloper** [comment]
Can you verify the server actually works? 

Yoshiki Vázquez-Baeza

**Comment by squirrelo** [comment]
Yes, it works fine.

**Comment by ElDeveloper** [comment]
Try to update your python and your pip, wheels should become available then ...

Yoshiki Vázquez-Baeza

**Comment by josenavas** [comment]
I'm still struggling with my error. Weirdly enough, I can start the server from an ipython session, but if I use the command line app it fails... probably a click problem... I'm investigating more...

**Comment by wasade** [comment]
@ElDeveloper, updated pip (which made things so much faster) but same error with psycopg2.

**Comment by adamrp** [comment]
Having recently upgraded to 10.10 myself, I'm running into some environment-related issues, but so far nothing new except for having to install XQuartz (which I believe was needed for mpl).

**Comment by ElDeveloper** [comment]
> @ElDeveloper, updated pip (which made things so much faster) but same error with psycopg2. 

I haven't hit that ever, the only reason why that was a problem some
times is because I didn't have pg_config and others in my path, thus the
reason why I added that to the INSTALL.md.

**Comment by wasade** [comment]
It is in my path, and does build. So unsure at the moment

**Comment by ElDeveloper** [comment]
So as far as I know only @squirrelo and me have been able to successfully get the package to install on their computers. The problems others are hitting are due to the dependencies and not to qiita itself?

**Comment by antgonza** [comment]
I agree with that statement. I think the most difficult part is getting cython/numpy/scipy/matplotlib installed, as expected.

**Comment by ElDeveloper** [comment]
@antgonza, did you try upgrading your pip?

**Comment by adamrp** [comment]
Yep, still hitting MPL issues. Currently, [this SO post](http://stackoverflow.com/questions/4092994/unable-to-install-matplotlib-on-mac-os-x) details the problem I'm having. Trying the soft link solution proposed by mhowison (second answer currently)

**Comment by wasade** [comment]
@antgonza, I only had an issue with cython first got. Second time around,
using an upgraded version of pip, did not have any issue with those libs.
My outstanding issue is psycopg2. But yes, in general agree the issues
appear to be dependencies.

**Comment by ElDeveloper** [comment]
Do you guys want to have a quick call to see if we can come up with a
solution, specifically so we can make the release?

**Comment by antgonza** [comment]
Just call me ...

**Comment by ElDeveloper** [comment]
I just pushed some additions to INSTALL.md, please let me know if you would like me to expand on something.

**Comment by josenavas** [comment]
Thanks @ElDeveloper I think those comments are enough!

**Comment by squirrelo** [comment]
Looks good to me

**Comment by wasade** [comment]
Agree, thanks!

**Comment by adamrp** [comment]
The install worked, but the `qiita` and `qiita_env` executables are not in my virtualenv's bin directory. This is not the case for @ElDeveloper. Am I the only one observing this?

**Comment by antgonza** [comment]
Those commands are available for my install ...

**Comment by ElDeveloper** [comment]
@antgonza just to confirm, when you call which qiita where does it point
to?

**Comment by antgonza** [comment]
My bad, same thing here. I got confused between environments.

**Comment by ElDeveloper** [comment]
@squirrelo, do you see the same problem?

**Comment by josenavas** [comment]
No issue here

**Comment by ElDeveloper** [comment]
I'm not seeing the problem either, when I do which qiita, I get the
expected path.

**Comment by ElDeveloper** [comment]
@antgonza, do you know if you are adding qiita/scripts to your PATH?
Maybe that's why it is showing in there?

**Comment by antgonza** [comment]
I am for my normal environment. What I did for this final test was to clone the repo from scratch and they created the tgz for install ... perhaps that's the issue?

**Comment by adamrp** [comment]
@ElDeveloper and I just had a call, and we realized that `pip install .` was not *actually* installing qiita-spots since it was "already satisfied" by my development version of qiita (which it found in my `PYTHONPATH` at /Users/adam/git/qiita). Running `pip install . -U` fixed the problem, and it now put the executables into my virtualenv as it did for everyone else. This is not something I think we need to add to the install instructions, since it was specific to my system and my `PYTHONPATH`. Thanks @ElDeveloper for all the help!

**Comment by ElDeveloper** [comment]
Thanks @adamrp, we are calling this good then. @antgonza and I are going to coordinate for the release ~2pm MST. :feet:

**Pull request merged**
