### PR TITLE
More moi - Josh & {Yoshiki, Antonio}

### PR DESCRIPTION
**Pull request by wasade**
Seems to work locally, so I expect travis to be happy.

### CODE REVIEW

**Comment by wasade** [comment]
...to add, please do not merge this after tests pass. Need to hook up the .js pulls from moi too.

**Comment by wasade** [comment]
Okay, AFAIK this is good. However, my local db was out of sync, and the test db doesn't have any data, so I haven't been able to take it through a meta analysis

**Comment by josenavas** [comment]
I'll try to test it later today. Useful if more than 2 developers fully check this.

**Comment by josenavas** [comment]
@wasade, in the waiting page for the the analysis, some of the status updates become links (not all of them - see image, the first one is a link while the second one is not). Also, the process looks like is stuck on this page, while before was redirecting to the 'done' page and the error was in there...

screen shot 2015-06-05 at 11 02 49 am

**Comment by wasade** [comment]
Fun. Is there a snapshot of real data that I can grab for my local system
for testing?

I won't be able to resolve this until sometime next week unfortunately

**Comment by josenavas** [comment]
These are the set of study files that I always use to test the interface.

[illumina_mult_lanes.tgz | uploaded via ZenHub](https://files.zenhub.io/5571e72e5079009502e1b301)

**Comment by wasade** [comment]
Currently getting the following with these data:

screen shot 2015-06-10 at 3 25 39 pm

**Comment by josenavas** [comment]
@wasade I might send you and older version of the files. I just tested this ones and I don't have any problem (the sample template raises a warning but it shouldn't block anything for testing)

[illumina_two_lanes.tgz | uploaded via ZenHub](https://files.zenhub.io/5578cd0bd947ac9f43fd19c4)

**Comment by wasade** [comment]
Are you sure the issue is moi? I couldn't load the second set of data without tinkering with it, and the error is not a moi error but a processing one:

```bash
********** afe89c8a-a912-49c3-abc1-ce34e1b633ef **********
context		: qiita_general
date_created	: 2015-06-11 14:16:47.970680
date_end	: 2015-06-11 14:16:48.302095
date_start	: 2015-06-11 14:16:47.976851
id		: afe89c8a-a912-49c3-abc1-ce34e1b633ef
name		: Build analysis
parent		: b462cf27-e2cc-40b0-af1d-84ce6a140f12
pubsub		: afe89c8a-a912-49c3-abc1-ce34e1b633ef:pubsub
status		: Failed
type		: job
url		: None
result		: Traceback (most recent call last):
  File "/Users/mcdonadt/ResearchWork/software/mustached-octo-ironman/moi/job.py", line 140, in _redis_wrap
    result = func(*args, **kwargs)
  File "/Users/mcdonadt/ResearchWork/software/qiita/qiita_ware/analysis_pipeline.py", line 41, in _build_analysis_files
    analysis.build_files(r_depth)
  File "/Users/mcdonadt/ResearchWork/software/qiita/qiita_db/analysis.py", line 727, in build_files
    self._build_biom_tables(samples, rarefaction_depth)
  File "/Users/mcdonadt/ResearchWork/software/qiita/qiita_db/analysis.py", line 776, in _build_biom_tables
    (self._id, dt))
  File "/Users/mcdonadt/ResearchWork/software/biom-format/biom/table.py", line 3535, in to_hdf5
    self.group_metadata(axis='observation'), 'csr', compression)
  File "/Users/mcdonadt/ResearchWork/software/biom-format/biom/table.py", line 3504, in axis_dump
    for category in md[0]:
IndexError: tuple index out of range
```

**Comment by josenavas** [comment]
Thanks for taking a look @wasade, there might be something wrong with the data/my system then.

@antgonza @ElDeveloper I know you guys have a good testing environment. Can you download this branch, install the latest version of moi and check that everything runs smoothly? It looks like so far I'm the only one who tried to test this branch with the latest MOI.

**Comment by antgonza** [comment]
There are conflicts. 

I tested locally and I was able to create a new study -> process it, and then run beta div. However, once all the analyses are ready the page doesn't move to the display page, it stays here: 
screen shot 2015-06-15 at 8 01 04 am

Once I click on the link the results seem fine.

**Comment by wasade** [comment]
Thanks @antgonza. Anything on the javascript console? I can't do anything locally without data that is usable..

**Comment by ElDeveloper** [comment]
I may have missed this, but can you use the data in test_data_studies?

**Comment by wasade** [comment]
Didn't know about that, thanks! Issue now is #1259

**Comment by wasade** [comment]
When trying to upload, I get "Not a valid extension: otu_table.biom"

**Comment by antgonza** [comment]
You need to add those by hand (we still do not have support for adding biom via the GUI) or use the files I sent  you ...

**Comment by ElDeveloper** [comment]
You should be able to run the commands.sh script and it should do the
thing with the things so you can do the thing.

**Comment by wasade** [comment]
@ElDeveloper, `commands.sh` didn't work, and seems to be a chicken/egg problem. I can't run it if I have a cluster up (as the cluster is connected to the database, so the database cannot be dropped), but the script depends on having a cluster up and running in order to complete (the `qiita db load_study` commands). Is this a known issue?

**Comment by ElDeveloper** [comment]
As long as you have a demo user I think it should be fine to comment the
lines that drop and create a new env (8 and 12) ... I think (can't check
right now though).

**Comment by wasade** [comment]
Okay, will try. Thanks

**Comment by wasade** [comment]
@antgonza, `moi_list` in moi 0.2.0 does not automatically set `window.location` on success. This is the correct behavior given that `moi_list` is designed to be a sidebar, not a full page like it presently is. I think it is out of scope of this PR to redo the analysis UI or to resolve UI job management fully on the site.

**Comment by josenavas** [comment]
This doesn't leave the system in an acceptable state, if that is outside of this PR, this cannot be merged in master. It has to go to a branch and then fix that behavior in another PR to that branch. Once everything is working correctly again, it can be merged in master.

**Comment by wasade** [comment]
It does work, just click the resulting link...

**Comment by josenavas** [comment]
I disagree on merging this into master: but the location of that link is not intuitive, not even consistent with what the rest of the page is showing (why only one success has the link? while not the others? why not a "go to results" link?).

I don't have any problem on merging this into another branch and fix this behavior on there, I disagree on master.

If other devs agree merging this on master it's fine, but this PR currently have my :-1: against master.

**Comment by wasade** [comment]
You can have as many links as you'd like, but these need to be created by the `ParallelWrapper`. The implicit redirect was not a good thing as it masked the state of the other jobs. We have never defined, or requested, sort order for the moi list so the order is runtime dependent. 

Given the goal of this PR, I argue that these changes are out of scope. Again, this PR is simply to bring qiita up to moi 0.2.0 which universally makes compute and debug easier. These changes do not break anything, the only UI difference is that an implicit redirect no longer happens, and in my opinion that is a good thing. 

It is presently difficult and tedious to debug compute in qiita. Sidelining this PR yields additional time wasted due to these difficulties. In addition, the existing compute system within qiita limited it to an uptime of 2 weeks, a problem that is ameliorated in this PR. The benefits of this PR vastly outweigh the minor change in UI behavior.

**Comment by wasade** [comment]
I think the redirect can be restored by overloading the moi_list.setResult
function. I can test this Monday.

**Comment by antgonza** [comment]
Thanks @wasade, that will be great so we can merge this PR.

**Comment by wasade** [comment]
Overloading the function does not work as the function is contained within
the `moi_list` namespace and I can't find a way to overload it external to
the namespace.

Again, I think the existing mechanism was not correct, and I do not think
it is worth investing much effort since the analysis waiting page is
something that we're revisiting anyway. In order to get this redirect to
work, which we're only going to remove later, it will take either a new
release of moi, or a custom "moi_list". Both are possible, but are
wasteful. Is this redirect really important enough to block given the
benefit of merge?

@ElDeveloper and @squirrelo, can you give :+1: or :-1: please?

**Comment by josenavas** [comment]
@wasade I don't mind about the redirecting as long as we have a single link to redirect that says something like "Go to results page". The problem is that is not intuitive at all right now...

**Comment by wasade** [comment]
Intuitive is subjective... but the text associated with creating the study has now been updated.

**Comment by ElDeveloper** [comment]
I was trying to test this out in my system and got the following error when I went to the studies list page:

```python
Traceback (most recent call last):
  File "/Users/yoshikivazquezbaeza/.virtualenvs/qiita/lib/python2.7/site-packages/tornado/web.py", line 1141, in _when_complete
    callback()
  File "/Users/yoshikivazquezbaeza/.virtualenvs/qiita/lib/python2.7/site-packages/tornado/web.py", line 1162, in _execute_method
    self._when_complete(method(*self.path_args, **self.path_kwargs),
  File "/Users/yoshikivazquezbaeza/.virtualenvs/qiita/lib/python2.7/site-packages/tornado/web.py", line 2297, in wrapper
    return method(self, *args, **kwargs)
  File "/Users/yoshikivazquezbaeza/git_sw/qiita/qiita_pet/handlers/study_handlers/listing_handlers.py", line 309, in get
    proc_samples=proc_samples)
  File "/Users/yoshikivazquezbaeza/git_sw/qiita/qiita_pet/handlers/study_handlers/listing_handlers.py", line 188, in _build_study_info
    proc_samples)
  File "/Users/yoshikivazquezbaeza/git_sw/qiita/qiita_pet/handlers/study_handlers/listing_handlers.py", line 90, in _build_single_study_info
    for pd_id in proc_datas])
  File "/Users/yoshikivazquezbaeza/git_sw/qiita/qiita_pet/handlers/study_handlers/listing_handlers.py", line 114, in _build_single_proc_data_info
    proc_info = proc_data.processing_info
  File "/Users/yoshikivazquezbaeza/git_sw/qiita/qiita_db/data.py", line 1414, in processing_info
    dynamic_info = dict(conn_handler.execute_fetchone(sql))
TypeError: 'NoneType' object is not iterable
ERROR:tornado.access:500 GET /study/search/?&user=demo@microbio.me&sEcho=783&query=&_=1435596740966 (::1) 28.56ms
```

Before testing I did `pip install -e . -U` from qiita's base directory. Did I miss something?

**Comment by wasade** [comment]
The branch you merged into was sane? This PR doesn't touch any of that
code, so that is pretty weird to see

**Comment by antgonza** [comment]
Did you restart ipython?

**Comment by ElDeveloper** [comment]
@wasade Good call, master doesn't seem to be working either.

@antgonza, yes I did.

@squirrelo, do you happen to have any ideas of what might be going on? I
also can't get to any study description page.

**Comment by josenavas** [comment]
@ElDeveloper do you think you're affected by this issue: https://github.com/biocore/qiita/issues/1308?

**Comment by ElDeveloper** [comment]
@josenavas, no, don't think so. The only username I have is
demo@microbio.me

**Comment by wasade** [comment]
Is there anything blocking this PR?

**Comment by josenavas** [comment]
@squirrelo can you test this PR please? Test running an analysis.
I've been testing this today and I had a weird behavior at the beginning, however I was unable to reproduce it so I'm assuming it was a dirty redis db or FS or database...

**Comment by josenavas** [comment]
BTW, make sure that your moi javascript is not catched, that might have been my issue...

**Comment by squirrelo** [comment]
Testing this and got a failure when running an analysis, but the analysis still says running on the analysis listing page. Is that something from this pull request or something entirely different?

**Comment by squirrelo** [comment]
Will say it works fine if all is success though.

**Comment by josenavas** [comment]
@squirrelo can you please double check? Did you had the developer console open? I had some odd behavior so if you also had it probably is because this doesn't work correctly, but I couldn't reproduce the error after I did some clean up. Please double check, this is important.

**Comment by squirrelo** [comment]
Still happening. Succes works fine, but failure makes it act odd. I think this is because the status set to error is not getting fired properly through `_failure_callback` in analysis_pipeline. Nothing shows on the dev console, so nothing I can trace. here is a gif:
qiita-analysis-moi-fail

**Comment by squirrelo** [comment]
Same thing is happening on my master branch too, so guess not an issue here. In light of that, :+1: ?

**Pull request merged**
