### PR TITLE
Queues for adding templates

### PR DESCRIPTION
**Pull request by josenavas**
Modifies the insertion of the templates to use the queue system. This will help to avoid the problem in which "floating" samples are added and cannot be automatically removed.

### CODE REVIEW

**Comment by ElDeveloper** [comment]
Looks great, only thing is: Do you think we could add a test to ensure the problem we were having doesn't come up again? Seems like a tricky test to design but would be nice to have it.

**Comment by josenavas** [comment]
I will try to add a test, although as you said, is going to be tricky...

**Comment by adamrp** [comment]
:+1: when tests pass.

**Comment by josenavas** [comment]
Does somebody knows a specific case where this issue was showing up? I'm having problems on defining that situation.

**Comment by adamrp** [comment]
I do not, sorry -- I think the queues should eliminate the possibility. Is deletion of md templates also taken care of via queue? If creation and deletion are both atomic operations (via queue), then the problematic situation should not be possible.

**Comment by ElDeveloper** [comment]
Yeah, I think you may be right. Do you agree @josenavas or did you find
a way? :O

**Comment by josenavas** [comment]
@antgonza helped me to find a way. Tests are added now

**Comment by josenavas** [comment]
BTW, I agree that it should not happen, but better to be sure with tests!

**Comment by josenavas** [comment]
This should be ready to go!

**Comment by antgonza** [comment]
:+1:

**Comment by josenavas** [comment]
@ElDeveloper can you take a quick look and merge if you think it is correct?

**Comment by ElDeveloper** [comment]
Looks good to me!

**Comment by ElDeveloper** [comment]
Thanks for figuring out a way to test this!

**Pull request merged**
