### PR TITLE
Add searching gif and feedback when search running. Fix #1069

### LINKED ISSUE #1069: Search on list_studies.html gives no visual feedback
Currently, if I do a search, there is no explicit visual feedback. There *might* be implicit feedback (if the search results in changes to the list of studies being displayed), but explicit feedback would be great (e.g., a very obvious/colorful/bold statement that indicates "Only showing studies that comprise samples hit by the following criteria: XXXXXXX").

Another improvement would be to show on this page how many of each study's samples are selected by the criteria specified.

### PR DESCRIPTION
**Pull request by squirrelo**
Does what it says on the tin.

### CODE REVIEW

**Comment by antgonza** [comment]
When I search on the study page I can't see the wait logo (even when doing large searches), where should it be? Note that I had to pull this to branch 1084-qiita-pet cause I have already applied the database changes.

**Comment by squirrelo** [comment]
It should be showing up under the search bar

**Comment by antgonza** [comment]
:disappointed: can't see it, have you tested with that branch?

**Comment by squirrelo** [comment]
not with that branch, no. I'll take a look

**Comment by squirrelo** [comment]
Should be good to go

**Comment by antgonza** [comment]
Thanks, it's working now. However, the search completed message is a bit misleading as the query finished but the rendering on the website is still not done. Not sure how to fix this, perhaps simply adding "Search complete (finishing rendering): query" .

**Comment by squirrelo** [comment]
That should not happen, as the render call happens before that text is added to the page.

**Comment by ElDeveloper** [comment]
I think this is working well, though I don't have enough studies to see the animated gif.

The only thing I wanted to bring up, is the fact that there's not enough feedback when two queries that retrieve no results are subsequently entered, see for example this:

feedback

It is only clear that something changed when you enter a query that retrieves studies, otherwise it's a bit hard to catch.

Perhaps using some sort of jQuery animations or highlighting that info box somehow else would do the trick.

**Comment by antgonza** [comment]
If you see @ElDeveloper's gif, he has the same behavior that I saw. The text under the text box says: "Search Completed: study_title includes soil" but the list still says "No studies found". In the next frame the studies appear.

**Comment by squirrelo** [comment]
His gif is actually working correctly, he just has no results found. I can add `(X studies found)` to the end of the search if it makes it clearer.

**Comment by squirrelo** [comment]
Now the page grays out when you search so that you know when the search is running and when you have results. Minimum of 400ms gray so no matter how fast the search completes you still see the gray out.

**Comment by ElDeveloper** [comment]
Awesome, thanks!

**Comment by ElDeveloper** [comment]
:+1:

**Pull request merged**
