### PR TITLE
Change typechecking to number from float

### LINKED ISSUE #938: processing sample template requires that latitude and longitude has a decimal
For example, ``latitude`` of 40 does not work, but 40.0 does work. Is this intentional, or that that requirement be relaxed?

### PR DESCRIPTION
**Pull request by adamrp**
Fix #938

### CODE REVIEW

**Comment by ElDeveloper** [comment]
@adamrp, just one minor thing, can you add a regression test for this problem?

**Comment by ElDeveloper** [comment]
:+1: otherwise.

**Comment by adamrp** [comment]
Thanks @ElDeveloper added regression test, and made some more modifications to the way the types are being checked

**Comment by ElDeveloper** [comment]
@adamrp this faliure is showing up in the Travis build, would you mind having a look?

```
======================================================================
FAIL: test_categories (qiita_db.test.test_metadata_template.DecoratedClass)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/biocore/qiita/qiita_db/test/test_metadata_template.py", line 1275, in test_categories
    self.assertEqual(obs, exp)
AssertionError: Lists differ: ['env_feature', 'description_d... != ['sample_id', 'season_environm...
First differing element 0:
env_feature
sample_id
Diff is 1213 characters long. Set self.maxDiff to None to see it.
```

**Comment by adamrp** [comment]
Okay, I think it should be good now!  Thanks for the reviews.

**Comment by wdwvt1** [comment]
:+1:

**Pull request merged**
