### PR TITLE
WIP: Fixes #1084

### LINKED ISSUE #1084: Being able to parse QIIME mapping files as sample templates
Ideally, a QIIME user will be able to upload a QIIME mapping file as a sample template. Since the QIIME mapping file already includes most of the prep template information, it will be useful to go one level up and create smart code that can check the sample template for columns that should be found in the prep template, and move them there.

### PR DESCRIPTION
**Pull request by josenavas**
This PR will fix #1084 

After discussing with @squirrelo and @ElDeveloper, we need a new branch to fix issue #1084. @ElDeveloper suggests (and @squirrelo and I agreed) that we should create a branch in upstream and do the PR, so we can keep track here of what needs to be done. I then will create small PR against this branch to fully fix #1084. Right now, this branch only includes a useless commit so I can do the PR.

The steps that need to be done to fix #1084 are:
- [x] Modify the DB so the PrepTemplate is connected directly to the study and we no longer need an intermediate RawData for this. The RawData then will just be hanging from the prep template, and it is acting solely as a container for the RawData files (looking at the SQL, there isn't any other information, so this makes perfect sense). `populate_test_db.sql` needs to be adapted.
- [x] Fix the code in `qiita_db/data.py` and tests
- [x] Fix the code in `qiita_db/metadata_template/prep_template.py` and tests
- [x] Fix the rest of the tests if any is failing.
- [x] Extend the parsing of the metadata template to accept QIIME mapping files. If a QIIME mapping file is passed, we extract the columns needed in the prep template, and create a new prep template at the same time that the sample template is created.
- [x] Modify the GUI, so we need to add a prep template first and then upload the raw data, rather than the other way around. This means changing the RawData tab for a PrepTemplate tab. A lot of people is confused with the RawData tab, so this will help avoiding that confusion.
- [ ] Fix any remaining bit (if any).
- [x] Remove unused files.
- [x] Update the CHANGELOG.md

If somebody sees a major problem with this, please comment here, as I'm going to start working on this right now.

### CODE REVIEW

**Comment by josenavas** [comment]
@antgonza @wasade @squirrelo @ElDeveloper @adamrp 

I found an issue that I'm not sure how to solve. I've checked in the live DB, and there are RawData objects that have files attached but they don't have a PrepTemplate. With the changes proposed here, we need a prep template to add a RawData.

What I'm proposing to solve this: Creating a prep template with almost no data to it. then the users can update the PrepTemplate as needed.

What do you think?

**Comment by ElDeveloper** [comment]
Hmmm, if they have no prep template attached to them, is there any way
we could simply just drop them? Granted that we verify why this is in
place. If we delete them, they are just going to move out to the
downloads folder right?

**Comment by antgonza** [comment]
Sorry for jumping on this until now. The issue on having the raw data linked to the prep template is for those cases that you have 2+ preparations on the same raw file (1 raw file -> multiple prep templates). I'm fine with the modifications if they account for this use case, can't tell from the description.

Anyway, I think unlinking them (they go back to the upload folder) is the way to go.

**Comment by ElDeveloper** [comment]
It would be great if @ackermag can confirm that this will not be a
problem.

**Comment by squirrelo** [comment]
@antgonza it actually makes that cleaner, since one prep template -> one raw data. It turns a one to many into a one to one relation.

**Comment by antgonza** [comment]
I think I'm not being clear. In some institutions by default they add 2+ preparations in a single raw data (for example: 16S, ITS, 18S) and my concern is that the user will need to upload 2+ times the same raw data so it is linked to each of the prep templates. Hope this is not the case ...

**Comment by josenavas** [comment]
@antgonza thanks for jumping in.

I think I did not added that to the description, but yes, I was thinking on taking that case into account. When the user wants to add a raw data to the prep template, the user will be asked if he wants to link a new raw data or if he wants to use an existing one, just as we are doing right now. Sorry for not being clear earlier!

**Comment by antgonza** [comment]
Thanks for the explanation, that seems fine. BTW do not forget to add these changes to the CHANGELOG.md

**Comment by josenavas** [comment]
Thanks @antgonza I've updated the PR comment to not forget about the changelog nore :smile:

**Comment by ackermag** [comment]
I am concerned about this because it is possible that some studies (from
qiime db) do have data and metadata that can be resolved.

On Thu, May 7, 2015 at 11:04 AM, Yoshiki Vázquez Baeza <
notifications@github.com> wrote:

> It would be great if @ackermag can confirm that this will not be a
> problem.
>
> On (May-07-15|10:59), Antonio Gonzalez wrote:
> > Sorry for jumping on this until now. The issue on having the raw data
> linked to the prep template is for those cases that you have 2+
> preparations on the same raw file (1 raw file -> multiple prep templates).
> I'm fine with the modifications if they account for this use case, can't
> tell from the description.
> >
> > Anyway, I think unlinking them (they go back to the upload folder) is
> the way to go.
> >
> > ---
> > Reply to this email directly or view it on GitHub:
> > https://github.com/biocore/qiita/pull/1163#issuecomment-99961693
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/biocore/qiita/pull/1163#issuecomment-99962659>.
>



-- 
Gail Ackermann
Knight Lab
UCSD
glackermann@ucsd.edu <ackermag@ucsd.edu>

**Comment by josenavas** [comment]
@ackermag I'm sorry I don't understand your comment.

**Comment by ackermag** [comment]
I am having trouble following the discussion - can we revisit in person
after I have done the more important irb submissions early tomorrow?


On Wed, May 20, 2015 at 10:20 PM, josenavas <notifications@github.com>
wrote:

> @ackermag <https://github.com/ackermag> I'm sorry I don't understand your
> comment.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/biocore/qiita/pull/1163#issuecomment-104140050>.
>



-- 
Gail Ackermann
Knight Lab
UCSD
glackermann@ucsd.edu <ackermag@ucsd.edu>

**Comment by josenavas** [comment]
Yes

**Comment by ElDeveloper** [comment]
I'm running a few tests on my system, so far everything looks good!

**Comment by ElDeveloper** [comment]
:+1:, this one is ready to go! I've tested a variety of things with this merged against the current master and it all seems to be working great! :clap: 

If someone else could test on their system, that would be fantastic.

**Comment by antgonza** [comment]
I was testing this and realized that I could not create a meta-analysis cause I get the following error:
```bash
WARNING:tornado.general:Invalid cookie signature 'ImFudGdvbnphQGdtYWlsLmNvbSI=|1432983435|184df5719feda3995cfda2175ca32be550d07fb3'
ERROR:tornado.application:Uncaught exception, closing connection.
Traceback (most recent call last):
  File "/Users/antoniog/.virtualenvs/qiita/lib/python2.7/site-packages/tornado/iostream.py", line 341, in wrapper
    callback(*args)
  File "/Users/antoniog/.virtualenvs/qiita/lib/python2.7/site-packages/tornado/stack_context.py", line 331, in wrapped
    raise_exc_info(exc)
  File "/Users/antoniog/.virtualenvs/qiita/lib/python2.7/site-packages/tornado/stack_context.py", line 302, in wrapped
    ret = fn(*args, **kwargs)
  File "/Users/antoniog/.virtualenvs/qiita/lib/python2.7/site-packages/tornado/httpserver.py", line 327, in _on_headers
    self.request_callback(self._request)
  File "/Users/antoniog/.virtualenvs/qiita/lib/python2.7/site-packages/tornado/web.py", line 1567, in __call__
    handler = spec.handler_class(self, request, **spec.kwargs)
  File "/Users/antoniog/.virtualenvs/qiita/lib/python2.7/site-packages/moi/websocket.py", line 23, in __init__
    self.group = Group(self.get_current_user(), forwarder=self.forward)
  File "/Users/antoniog/.virtualenvs/qiita/lib/python2.7/site-packages/moi/group.py", line 50, in __init__
    for node in self._traverse(self.group):
  File "/Users/antoniog/.virtualenvs/qiita/lib/python2.7/site-packages/moi/group.py", line 60, in _traverse
    details = self._decode(r_client.get(current_id))
  File "/Users/antoniog/.virtualenvs/qiita/lib/python2.7/site-packages/moi/group.py", line 81, in _decode
    raise ValueError("Unable to decode data!")
ValueError: Unable to decode data!
ERROR:tornado.application:Exception in callback <functools.partial object at 0x10b158ba8>
Traceback (most recent call last):
  File "/Users/antoniog/.virtualenvs/qiita/lib/python2.7/site-packages/tornado/ioloop.py", line 458, in _run_callback
    callback()
  File "/Users/antoniog/.virtualenvs/qiita/lib/python2.7/site-packages/tornado/stack_context.py", line 331, in wrapped
    raise_exc_info(exc)
  File "/Users/antoniog/.virtualenvs/qiita/lib/python2.7/site-packages/tornado/stack_context.py", line 302, in wrapped
    ret = fn(*args, **kwargs)
  File "/Users/antoniog/.virtualenvs/qiita/lib/python2.7/site-packages/tornado/iostream.py", line 341, in wrapper
    callback(*args)
  File "/Users/antoniog/.virtualenvs/qiita/lib/python2.7/site-packages/tornado/stack_context.py", line 331, in wrapped
    raise_exc_info(exc)
  File "/Users/antoniog/.virtualenvs/qiita/lib/python2.7/site-packages/tornado/stack_context.py", line 302, in wrapped
    ret = fn(*args, **kwargs)
  File "/Users/antoniog/.virtualenvs/qiita/lib/python2.7/site-packages/tornado/httpserver.py", line 327, in _on_headers
    self.request_callback(self._request)
  File "/Users/antoniog/.virtualenvs/qiita/lib/python2.7/site-packages/tornado/web.py", line 1567, in __call__
    handler = spec.handler_class(self, request, **spec.kwargs)
  File "/Users/antoniog/.virtualenvs/qiita/lib/python2.7/site-packages/moi/websocket.py", line 23, in __init__
    self.group = Group(self.get_current_user(), forwarder=self.forward)
  File "/Users/antoniog/.virtualenvs/qiita/lib/python2.7/site-packages/moi/group.py", line 50, in __init__
    for node in self._traverse(self.group):
  File "/Users/antoniog/.virtualenvs/qiita/lib/python2.7/site-packages/moi/group.py", line 60, in _traverse
    details = self._decode(r_client.get(current_id))
  File "/Users/antoniog/.virtualenvs/qiita/lib/python2.7/site-packages/moi/group.py", line 81, in _decode
    raise ValueError("Unable to decode data!")
ValueError: Unable to decode data!
```
I tried with my old version of moi, then installed the new one and same error. Not sure what's the problem ...

**Comment by ElDeveloper** [comment]
Meta analyses are working for me without a problem. Haven't updated moi though. Maybe try restarting redis? (i know that's not the best but ...).

Yoshiki Vázquez-Baeza

**Comment by ElDeveloper** [comment]
I just updated moi and it the analysis pipeline is still working. Note
that you may have had an old version of moi that wasn't working (still
had known issues) and left the redis database in an unstable state(?)

**Comment by wasade** [comment]
@antgonza, are you expecting to be using the development version? if so,
then that traceback indicates you have an out-of-date build on your system
as `_traverse` no longer exists

**Comment by josenavas** [comment]
When I first tried I was able to reproduce the error. I then updated moi and cleaned up the redis database and I didn't had any problem...

**Comment by antgonza** [comment]
I can confirm that is working.

**Comment by josenavas** [comment]
Thanks to all the reviewers! Excited to get this into the system!

**Comment by squirrelo** [comment]
Can we get this deployed before noon tomorrow? Then I can demo it for VROOM team.

**Comment by antgonza** [comment]
Done with the help of @josenavas

**Pull request merged**
