### PR TITLE
ENH: Change phrasing of upload text

### PR DESCRIPTION
**Pull request by ElDeveloper**
As per a user's request (on the help account).

### CODE REVIEW

**Comment by antgonza** [comment]
Looks good but could you do your PR against dev? Thanks!

**Comment by antgonza** [comment]
I moved it but you will need to push a change to restart travis, could you? If you need something easy to change: https://github.com/biocore/qiita/issues/2259

**Comment by ElDeveloper** [comment]
@antgonza should be fixed.

**Comment by antgonza** [comment]
Looks good, gonna wait for test ...

**Pull request merged**
