### PR TITLE
fix #1015

### LINKED ISSUE #1015: tabs in study description
In most use cases, based on my last few week tests, the user will be mainly working on the last object added into a working tab. Thus, when clicking on a tab in the study description (let's say: Processed data) the focus should be in the last tab within the new tabs vs. the first one. This should make it more user friendly.

### PR DESCRIPTION
**Pull request by antgonza**
Fixing #1015 and making sure that when displaying the tabs are always in ascending order by id.

### CODE REVIEW

**Comment by josenavas** [comment]
Thanks @antgonza :+1: 

Just to throw an idea, and let's see what you and others think. I think it will be useful to add a 'name' property to the PrepTemplate/RawData/PreprocessedData/ProcessedData objects, and we can use that to name the tabs. We can probably limit that to ~10 chars or so. It will make live easier to the users to identify the object that they are working with.

**Comment by antgonza** [comment]
Agree, basically expand: https://github.com/biocore/qiita/issues/597

**Comment by josenavas** [comment]
Thanks @antgonza, i've commented on that issue

**Comment by ElDeveloper** [comment]
:+1: works like a charm, question. Should this be added to the ChangeLog? We kinda need to know what things to describe there and what things not to.

**Comment by antgonza** [comment]
I do not feel this change is ChangeLog worth ... IMOO we should add only things that are huge improvements, bugs, or GUI changes.

**Pull request merged**
