### PR TITLE
A couple of small fixes

### PR DESCRIPTION
**Pull request by josenavas**
This depends on https://github.com/biocore/qiita/pull/1800 so review/merge that one first.

This are a couple of fixes that have been identified after deploying this branch in the test environment and testing there.

### CODE REVIEW

**Comment by josenavas** [comment]
Ready for review/merge

**Comment by antgonza** [comment]
👍 @ElDeveloper, could you take a look? Thanks!

**Comment by josenavas** [comment]
@ElDeveloper can you take a quick look into this?

**Comment by josenavas** [comment]
Hey @biocore/qiita-dev I would like to have this merged so I can take the qiita_client code out of this repo for my meeting at 9 with Greg...

**Pull request merged**
