### PR TITLE
Update INSTALL.md for pgbouncer

### PR DESCRIPTION
**Pull request by squirrelo**
Add pgbouncer install instructions.

### CODE REVIEW

**Comment by squirrelo** [comment]
Stupid longitude error in tests. Good to go.

**Comment by antgonza** [comment]
Could you add an example of how to configure it on a local machine? I do not think every user should need to read a huge config page and explanation so they can start using pgbouncer with their local install. Similar to the [nginx](https://github.com/biocore/qiita/blob/master/qiita_pet/nginx_example.conf) example.

**Comment by squirrelo** [comment]
I am against having to keep documentation up to date for a project we do not control or work on. There is an example minimal configuration at the bottom of https://pgbouncer.github.io/config.html  I can point to that if we absolutely need an explicit example.

**Comment by wasade** [comment]
We also don't provide install information for Centos, how to configure your
firewall, etc. This really is site specific and there is no aspect of qiita
that depends on it.

**Comment by adamrp** [comment]
I also wanted to make a note of [this question in the pgbouncer FAQ](https://pgbouncer.github.io/faq.html#should-pgbouncer-be-installed-on-webserver-or-database-server%3F), particularly this part:

> Installing on webserver is good when short-connections are used, then the connection setup latency is minimised - TCP requires couple of packet roundtrips before connection is usable. Installing on database server is good when there are many different hosts (eg. webservers) connecting to it, then their connections can be optimised together

For our purposes, it seems like we want to install pgbouncer on the webserver (and not the database server).

**Comment by antgonza** [comment]
Note that IMOO this is a completely different issue from @wasade examples. I think this is different because this fixes (at least we think) the speed problem in loading studies. Note that this will be an issue to every single user that wants to develop using the EMP as an initial dataset, which take ~9 secs to load.

**Comment by squirrelo** [comment]
Yeah, I talked to Jeff briefly before the lab meeting about setting it up
on the webserver. I or someone else should follow up.

**Comment by wasade** [comment]
We do have quite a few connections coming from ipengines and AG, but don't
have practical experience to know where the balance point is

**Comment by squirrelo** [comment]
pgbouncer runs on a per-database level as well it looks like, so we can have it specifically for qiita on the qiita webserver.

**Comment by wasade** [comment]
@antgonza, if the inclusion criteria is based on performance, then should we include tips on optimizing postgres, hardware choices, filesystem tuning, kernel tuning, etc? 

The document describes this as "for large-scale systems" which implies that there is someone who has sysadmin experience on the deployment end. While this is a piece of documentation, we need to minimize the chance of it being out of sync with a project that we have no involvement in, otherwise it will become an incorrect piece of documentation. 

I think @squirrelo's suggestion of linking out is acceptable here.

**Comment by antgonza** [comment]
I think making users and admins life easier is a good idea. If you have suggestions to make qiita run better I'm all about creating a section for this. 

BTW I completely disagree that this install is only for large-scale systems. If you remember the reason we catch this before deploy is because I have the EMP studies in my laptop, which IMOO should be the regular deploy environment.

**Comment by wasade** [comment]
It only makes their lives easier if the documentation is ensured to be
correct.

As the PR is presently written, it is describing pgbouncer for use in
large-scale systems.

On Tue, Apr 28, 2015 at 10:01 AM, Antonio Gonzalez <notifications@github.com

**Comment by antgonza** [comment]
Agree on correctness, and that's a commitment we have to make on all our tools.

@squirrelo could you change your PR so it reflects @wasade's point about large-scale systems? Which is incorrect.

**Comment by squirrelo** [comment]
I think you are optimizing for an edge case here, since yes, it's for systems with a large amount of studies in them. If we are saying the normal install is on a laptop, that means most likely for working on your personal studies. I think it's safe to leave it as large scale for now, or change the wording to "hundreds of studies" and revisit later if necessary.

**Comment by wasade** [comment]
It's also why we historically have not done things like describing site
specific optimizations...

I wasn't suggesting changing it away from large-scale, but that's just my
opinion.


On Tue, Apr 28, 2015 at 10:05 AM, Antonio Gonzalez <notifications@github.com

**Comment by antgonza** [comment]
@wasade: I think qiita is a different piece of software of what we have done before and that it needs way more documentation for regular users. Thus, parting from what we have done before so we can reduce possible user and developer bad experiences is the way to go.

@squirrelo: this is an issue even with the test dataset (1-2 studies), as it take ~3 secs to load. Also remember that the plan is to allow users to perform meta-analysis, at least with the EMP.

**Comment by josenavas** [comment]
My 2 cents:

I completely agree with @antgonza. I can see questions coming from users like: why qiita takes so long to load my study page? The EMP studies are only 100, and I can see people easily reaching this numbers. I've not been involved in too many analysis and I can tell that I would already have ~25 studies.

I think we should include at least the minimal instructions required to make Qiita usable. If somebody has a special machine, we can then point the actual pgbouncer documentation.

We should be realistic and understand that we are going to deal with non-computer experts users, so adding this documentation will make our lives easier in the long run.

**Comment by wasade** [comment]
It took ~3 seconds for me to retrieve all the public studies on
qiita.microbio.me, I didn't do that locally or on a test dataset.





On Tue, Apr 28, 2015 at 10:13 AM, Antonio Gonzalez <notifications@github.com

**Comment by adamrp** [comment]
@josenavas @antgonza I think the point that @wasade is making (which I agree with) is that we should reference pgbouncer's own documentation (which is going to be far more detailed, comprehensive, up-to-date, and accurate than we can hope to duplicate) rather than re-iterate the same instructions in our own words. We have to trust that our users can follow others' instructions as well as they would be able to follow our own.

**Comment by squirrelo** [comment]
Also note, if we are going to write this for non-expert computer users (biologists, biochemists, etc) Then the source code, make, make install, all of it is way too technical for a standard user. In fact, a lot of the documentation is daunting when looked at by a non-technical computer user.

**Comment by antgonza** [comment]
Wanna have a call?

**Comment by wasade** [comment]
@antgonza, the profiling data yesterday wasn't for loading studies

**Comment by wasade** [comment]
I can talk briefly

**Comment by josenavas** [comment]
I can talk too

**Comment by squirrelo** [comment]
From the call, it sounded like we no longer need this pull request?

**Comment by antgonza** [comment]
yup

**Pull request closed without merging**
