### PR TITLE
Fixing system encoding so UTF-8 is supported for everything

### PR DESCRIPTION
**Pull request by josenavas**

### CODE REVIEW

**Comment by squirrelo** [comment]
Is there a way to test this or, alternately, have printed out in test_qiita_env?

**Comment by antgonza** [comment]
What do you want to test?

**Comment by squirrelo** [comment]
Make sure that UTF-8 is set. Probably useful to output encoding on qiita_test_install.

**Comment by josenavas** [comment]
@squirrelo Added to qiita_test_install

**Comment by squirrelo** [comment]
:+1:

**Comment by wasade** [comment]
awesome!

**Pull request merged**
