### PR TITLE
Remove 100 character limit on table

### LINKED ISSUE #785: Sample template headers are limited in length
I'd like to have the full OTU taxonomic assignment (down to genus) as a header and the corresponding relative abundances of that OTU in each sample filling down the column in the sample template so that I can color PCoA plots by OTU abundance later on. However, I get this error message upon submitting my sample template.

"Error running SQL query: INSERT INTO qiita.study_sample_columns (study_id, column_name, column_type) VALUES (%s, %s, %s) ARGS: [(10080, 'root_p__cyanobacteria_c__chloroplast_o__streptophyta_f___g__', 'float8') 
# Insert rest of my long headers here
] Error: value too long for type character varying(100)

Is it possible to allow longer headers?

Thanks!

### PR DESCRIPTION
**Pull request by adamrp**
Fix #785

### CODE REVIEW

**Comment by wasade** [comment]
:+1:, build failures though that do appear to be real

**Comment by adamrp** [comment]
The unit tests are passing, so unless there are further comments this should be good to merge

**Comment by ElDeveloper** [comment]
We can safely ignore the coveralls failures.

**Comment by ElDeveloper** [comment]
I'm about to test this in my machine though.

**Pull request merged**
