### PR TITLE
added delete buttons on show_analyses page

### PR DESCRIPTION
**Pull request by RNAer**
Each analysis can be deleted on that page.

my first commit to qiita, yay! Thanks Jose for answering my questions - it is tremendously helpful!

### CODE REVIEW

**Comment by josenavas** [comment]
@RNAer you have flake8 errors. Run `flake8 qiita_* setup.py scripts/qiita scripts/qiita-env scripts/qiita-test-install` on your machine to get a list of problems.

Thanks!

**Comment by josenavas** [comment]
Fixes https://github.com/biocore/qiita/issues/1358 and https://github.com/biocore/qiita/issues/1235

@RNAer if you use `fixes #<issue num>` the issue will get automatically closed once this is merged.

**Comment by squirrelo** [comment]
One last comment: The delete button shouldn't be shown if the analysis status is `running` since deleting a running analysis can cause serious problems.

**Comment by squirrelo** [comment]
Other than that, looks really good!

**Comment by RNAer** [comment]
@squirrelo which line are you talking about? I only see one `analysis.name`.

**Comment by josenavas** [comment]
@squirrelo It's only used 2 times in the execution of the method, it appears more times but it is in a mutually exclusive if statement.

**Comment by squirrelo** [comment]
OK, then just need to remove button if running.

**Comment by RNAer** [comment]
updated. flake8 checks fine. the button is invalid when the study is running.

**Comment by josenavas** [comment]
:+1: waiting for the tests to pass

**Comment by josenavas** [comment]
Thanks @RNAer you're officially a qiita developer! Welcome!!

**Pull request merged**
