### PR TITLE
DB CHANGES: Analysis collection object

### PR DESCRIPTION
**Pull request by squirrelo**
This adds 5 new tables for the collections object. One tracks the main info, one tracks status, one allows sharing, one tracks analyses added to the collection, and one tracks jobs highlighted as important to the collection.

### CODE REVIEW

**Comment by squirrelo** [comment]
DB changes for #857

**Comment by squirrelo** [comment]
Travs is apparently having a bad day and not updating github with final status, so I'll manually say that all tests passed and this is good to review.

**Comment by josenavas** [comment]
I just take a quick look. Why do you need the collection-job table? You should have `collection<->analysis<->job` so the `collection<->job` is redundant...

**Comment by squirrelo** [comment]
collecton<->job is so you can highlight specific jobs as important to the analysis, e.g. the alpha diversity in analysis 1 is a figure I want in a paper, and the beta diversity from analysis 2. This can then all be dropped on a single page for overview.

**Comment by josenavas** [comment]
uhmmm... ok I'm still wrapping this on my mind... Probably better to change the name of the table (e.g. important jobs) and put collection_id, analysis_id and job_id so we can ensure some integrity with the data (you can potentially try to match a job that does not belong to that colleciton)

**Comment by squirrelo** [comment]
OK, can do.

**Comment by squirrelo** [comment]
After trying to find a way to do this integrity check with foreign keys, it looks like we're going to have to do that integrity check with python. Altering the table to have analysis_id would just be redundant with the collection_analysis table data in that case.

**Comment by josenavas** [comment]
We have not been using triggers so far on the project... what other people think about creating integrity checkers using triggers? http://www.postgresql.org/docs/9.1/static/sql-createtrigger.html

**Comment by squirrelo** [comment]
So reading this, it would be
```SQL
CREATE TRIGGER insert_collection_job
    BEFORE INSERT ON collection_job
    FOR EACH ROW
    EXECUTE PROCEDURE check_collection_access();
```
With `check_collection_access()` being a check to make sure the analysis the job is in is part of the collection.

**Comment by squirrelo** [comment]
Do we have a way of putting procedures in the database using patches currently?

**Comment by wasade** [comment]
Patches execute arbitrary sql, so yes. However, this did not seem to work properly for AG web. Not sure if its due to schemas or not.

**Comment by josenavas** [comment]
@squirrelo which is the status of this? I need to modify the database too, and I don't want to throw away all your code. However, I need an ETA, as the changes that I need to do they have some kind of time pressure

**Comment by squirrelo** [comment]
Triggers in postgres are tricky, but  I should have it in by end of day.

**Comment by josenavas** [comment]
Thanks!!

**Comment by squirrelo** [comment]
This is good to go.

**Comment by josenavas** [comment]
@squirrelo can you add a test to check that the actual trigger works?

**Comment by squirrelo** [comment]
They're already in there. `test_sql.py`

**Comment by josenavas** [comment]
Ooops ok! For some reason it was not showing (or I did not see it...) :+1:

**Pull request merged**
