### PR TITLE
Move generic navbar links to far left

### PR DESCRIPTION
**Pull request by adamrp**
Also some minor modifications to the navbar links.

### CODE REVIEW

**Comment by squirrelo** [comment]
:+1:

**Comment by ElDeveloper** [comment]
... the PR looks fine and the code works as expected, however I don't like that the first option you get when you are logged in is Help, Stats, GitHub and finally the actually useful things like Meta Analysis, Study and Admin. :-1: to this change.

**Comment by antgonza** [comment]
I think  the best will be to have 3 sections: user menu, login, and other.
- menu: create account, reset forgotten passwd, when not log in;
metaanalysis, study, etc once you are log in
- login: login text and button when not log in; email with account
update when log in
- other: stats, help, etc.

what do you guys think?

**Comment by ElDeveloper** [comment]
I like the organization as is, but perhaps the only group that we should
create is "Other", here's where Stats, Help, and GitHub could live.

**Comment by squirrelo** [comment]
I'd rename "Other" to "Info" or "Help" but :+1: to @ElDeveloper idea of leaving as is but condensing the three others.

**Comment by antgonza** [comment]
Note that the sections do not need to be labeled, is just grouping so
the last (other) stays static to the right.

**Comment by adamrp** [comment]
There is no separator to create sections, and bootstrap will resize things based on screen real estate, so I don't think it's feasible to create 3 different sections that will dependably display consistently.

@ElDeveloper by a "separate group" for Stats, Help, and Github, do you mean another dropdown?

**Comment by ElDeveloper** [comment]
Yes, that's what I mean. Sorry for not being clear.

**Comment by adamrp** [comment]
Is this better?

**Comment by ElDeveloper** [comment]
:+1: I like this a lot more!

**Pull request merged**
