### PR TITLE
fix #2225 and partial #2224

### LINKED ISSUE #2225: Studies view-change section labels
"Your Studies (includes shared with you)" should be changed to  "Your Studies". Implemented in conjunction with https://github.com/biocore/qiita/issues/2224, it should be clear to users that this includes studies shared with them.

"Other Studies" should be changed to "Public Studies".

### PR DESCRIPTION
**Pull request by antgonza**

### CODE REVIEW

**Comment by josenavas** [comment]
@antgonza please remove the code relevant to #2224 as it isn't clear if we actually are going to solve that.

**Comment by antgonza** [comment]
OK, I think we agreed on showing the owners email, and just for clarity is gonna look like this: 
screen shot 2017-08-17 at 8 33 26 am

**Comment by josenavas** [comment]
@antgonza See my comment on the issue. Everybody on the meeting was strongly agreeing on NOT showing the email, but just the name. Please, update accordingly. Is just one more join.

**Comment by antgonza** [comment]
k, change made. Now:
screen shot 2017-08-17 at 9 45 15 am

**Comment by antgonza** [comment]
Ready for review!

**Comment by wasade** [comment]
:+1:

**Comment by adswafford** [comment]
Excellent. Thanks!

**Pull request merged**
