### PR TITLE
Change the example email address, remove colorado

### PR DESCRIPTION
**Pull request by adamrp**
tangentially related to #1413

### CODE REVIEW

**Comment by antgonza** [comment]
:+1: when tests pass.

**Comment by ElDeveloper** [comment]
:+1:

**Comment by josenavas** [comment]
Should we actually put something that we do not control? I'm wondering if somebody has a custom installation for their lab we might not want to receive all the internal emails...

**Comment by antgonza** [comment]
Excellent point! However, that email is only used as the email that emails as sent as. I'm OK either way.

**Comment by adamrp** [comment]
I don't feel strongly, and would be fine changing it to something like "example@domain.com" or something. The `EBI_ORGANIZATION_PREFIX` is also currently set to qiime; do we want to change this, too, so that the example configuration doesn't contain other information specific to the knight lab or UCSD?

**Comment by antgonza** [comment]
I think these change will make it more generic, which is good ...

**Comment by ElDeveloper** [comment]
Yes, I also think those sound like good changes!

**Pull request merged**
