### PR TITLE
Make sure processed data exists before displaying datatype. Fix #784

### LINKED ISSUE #784: Searching studies with multiple datatypes can error
If you have a study with processed data of one data type (say 16S) and just raw data/preprocessed data  of another type (say ITS), searching for that study will give you an error. This comes from the fact that the study says it has ITS data, but it is not completely processed yet.

### PR DESCRIPTION
**Pull request by squirrelo**
this adds an if statement to make sure we don't index a non-existant list.

### CODE REVIEW

**Comment by antgonza** [comment]
This works as expected but why solve this after the query is retrieved vs. solving within the query?

**Comment by squirrelo** [comment]
Because I'm trying to leave the search functionality as generic as possible so it can be used for other things besides just the analysis pipeline.

**Comment by antgonza** [comment]
Not sure that's the way to go. In previous experiences, we have seen that this kind of generalization causes performance bottlenecks. We can discuss during today's meeting.

**Comment by squirrelo** [comment]
This is literally just adding an if statement. Not sure how that causes a performance bottleneck.

**Comment by antgonza** [comment]
Got it, thought the loop was on the studies, which can be a large
number, vs. the datatypes that is minimal and my concern is looping on
all the studies and discarding those that do not satisfy the if
statement.

**Comment by squirrelo** [comment]
Ok. I'm adding another fix in here really fast and then it should be ready to go.

**Comment by antgonza** [comment]
Thanks.

**Comment by squirrelo** [comment]
Good to go once tests pass

**Comment by antgonza** [comment]
Tests not passing.

**Pull request merged**
