### PR TITLE
fixing (the) future

### PR DESCRIPTION
**Pull request by antgonza**

### CODE REVIEW

**Comment by antgonza** [comment]
@biocore/qiita-dev can we get a couple of reviews here? This fixes the future and new biom issues in qiita.

**Comment by josenavas** [comment]
Shouldn't six be in the setup.py now?

**Comment by antgonza** [comment]
We have been using six for other things AKA I didn't introduce this dependency. My guess is that is being installed by other at installation.

**Comment by josenavas** [comment]
Well, accordingly to the code we where using future.utils.six. If six is now a direct dependency of Qiita, it should be in the setup.py. I think it is not safe to assume that it gets installed by one of our dependencies.

**Comment by squirrelo** [comment]
it’s an python dependency, but would still be good to explicitly install it here.

**Comment by antgonza** [comment]
I can add if that's what we agree on. However, I feel that we should keep relaying on ipython to install it as this way we are sure to not have any version conflicts, what do you think?

**Comment by josenavas** [comment]
I would recommend against it, in case that Ipython drops such dependency, we will be missing it. However, if others agree with this solution ok with me.

**Comment by wasade** [comment]
Isn't six part of future?

**Comment by antgonza** [comment]
Not since 0.14 ...

**Comment by wasade** [comment]
Pretty sure the string io imports can be made from "io" which is a built in
module. See how we did it in biom

**Comment by antgonza** [comment]
Tried io but all tests are using strings and io.StringIO expects unicode. Then realized that in other sections of qiita we were using from six so decided to go that route.

**Comment by josenavas** [comment]
I think you just need to add a `u` in front of the strings so they're unicode.

**Comment by wasade** [comment]
Yes

**Comment by Jorge-C** [comment]
Or even importing unicode_literals from __future__. Good overview of the
advantages / drawbacks of the two approaches here
http://python-future.org/unicode_literals.html

**Comment by antgonza** [comment]
I can move back and add a u or use unicode_literals but not sure what's the benefit over six?

**Pull request merged**
