### PR TITLE
ipython 2.4.1

### PR DESCRIPTION
**Pull request by antgonza**

### CODE REVIEW

**Comment by antgonza** [comment]
Ready for review.

**Comment by squirrelo** [comment]
:+1:

**Comment by wasade** [comment]
2.4.1 <= x < 2.5

Would be better, unless we think we will go to 3.0 on very short order

**Comment by squirrelo** [comment]
My understanding is we're going to be on 3.0 as fast as we can, and this is a stopgap.

**Comment by antgonza** [comment]
@squirrelo I already made @wasade suggestion and the test pass. I think is fine to validate that range and simply change to 3.0 once our code supports it.

**Comment by squirrelo** [comment]
Works for me.

**Pull request merged**
