### PR TITLE
DOC: Add missing tutorial file

### PR DESCRIPTION
**Pull request by ElDeveloper**

### CODE REVIEW

**Comment by antgonza** [comment]
:+1:

**Comment by josenavas** [comment]
@antgonza this is still applies taking into account your work in #1258?

**Comment by antgonza** [comment]
Yup, cause this is for files from which we can extract barcodes and #1258 is for those that we can't.

**Comment by josenavas** [comment]
Oh, ok. :+1: the once tests pass.

**Comment by josenavas** [comment]
That was a really bad wording: :+1: once the tests pass
hahah

**Pull request merged**
