### PR TITLE
Stop failures maybe?

### PR DESCRIPTION
**Pull request by squirrelo**

### CODE REVIEW

**Comment by ElDeveloper** [comment]
Let's repeat this build a few times.

**Comment by adamrp** [comment]
@ElDeveloper :+1:

**Comment by squirrelo** [comment]
This has passed 4 restarts. If it passes this one, I've got the solution and this should be merged. Note this permanently turns off debug mode though, so any changes will require a server restart to see.

**Comment by antgonza** [comment]
NOOOOOOOOOOO!! Any way to have both?

**Comment by squirrelo** [comment]
OK, so here's the gist (hah) of what's going on: In debug mode a poll is added to the ioloop to check files every half second for updates. Since we have so many tests, the checks pile up and end up choking the system and it times out. I've looked into forcing debug to false on the tests, but it seems to be read-only once created. I'll look a little further, but if I can't find a solution tonight this is more critical to merge as is, in my opinion.

**Comment by squirrelo** [comment]
Sometimes the docs are wrong apparently. I can force it because it's just a dict. Ready to go once tests pass.

**Comment by squirrelo** [comment]
Going to close this and open a new one since this was more an exploratory branch.

**Pull request closed without merging**
