### PR TITLE
BLD/TST: Add travis_retry to .travis.yml

### PR DESCRIPTION
**Pull request by ElDeveloper**
Prefix some installation commands that are known to spuriously fail.

### CODE REVIEW

**Comment by ElDeveloper** [comment]
I'm starting to believe the failures we see in other builds are due to the fact that more people uses Travis CI at those time of the day, unlike this time ... just sayin' :8ball:

**Comment by josenavas** [comment]
Is there any statistics page? We can potentially check our failures and try to correlate it with the usage...

**Comment by ElDeveloper** [comment]
Yes http://www.traviscistatus.com

Yoshiki Vázquez-Baeza

**Comment by josenavas** [comment]
buff... it looks like from 6 to ~4 they're running the system as its maximum capacity! Impressive! It looks like there is still some more room on the container based ones, so I hope we get more lucky using those ones!

**Comment by ElDeveloper** [comment]
Yeah, it seems like that's the case.

**Comment by josenavas** [comment]
:+1:

**Pull request merged**
