### PR TITLE
Sync with master

### PR DESCRIPTION
**Pull request by antgonza**
This one is actually going to ebi-improvements and is jus syncing to master.

### CODE REVIEW

**Comment by josenavas** [comment]
@antgonza, where there any merge conflicts?

**Comment by antgonza** [comment]
Nop, just rather have it sync before there are any ... better safe than sorry. I will create a PR with my actual changes in a second.

**Comment by josenavas** [comment]
Thanks, in that case I will just merge them, sounds good?

Before creating your other PR, can you create the PR from upstream ebi-improvements to upstream master? In that PR we can list the things that remains to be done. It will get automatically updated as we are merging the remaining PR.

**Comment by antgonza** [comment]
Yup and yup.

**Comment by josenavas** [comment]
Thanks!

**Pull request merged**
