### PR TITLE
@squirrelo and @ElDeveloper were complaining

### PR DESCRIPTION
**Pull request by adamrp**

### CODE REVIEW

**Comment by squirrelo** [comment]
:+1:  to OCD!

**Comment by josenavas** [comment]
Why is that space being removed? There are a lot of instances of that space and the reason is that the interface looks way better with that space. Otherwise, the text looks too close to the icon...

**Comment by ElDeveloper** [comment]
I disagree, the interface looks misaligned, I think that's why @adamrp is removing it.

Yoshiki Vázquez-Baeza

**Comment by adamrp** [comment]
@josenavas look at the page currently with the space and you'll see.
@eldeveloper that's exactly right.

**Pull request merged**
