### PR TITLE
DOC: Add note about reserved words

### PR DESCRIPTION
**Pull request by ElDeveloper**

### CODE REVIEW

**Comment by antgonza** [comment]
👍

**Comment by antgonza** [comment]
@tanaes I _think_ I just gave you merge permissions, can you try merging?

**Comment by tanaes** [comment]
Still seeing 'Only those with write access can...' 

But Travis is still in progress, so maybe after it finishes it will let me.

**Comment by antgonza** [comment]
@tanaes, it was something else with the permissions, you should be able now.

**Comment by tanaes** [comment]
thanks @antgonza !

**Pull request merged**
