### PR TITLE
FIX: typos

### PR DESCRIPTION
**Pull request by jenwei**
Combed through `qiita_pet/templates` and fixed two typos.

### CODE REVIEW

**Comment by josenavas** [comment]
Thanks for your contribution @jenwei !

It looks like the errors are unrelated to your changes, so don't worry about them.

@wasade, @gregcaporaso it looks like the errors in here are related with the changes in biom - can you guys take a look?

**Comment by jenwei** [comment]
Happy to help @josenavas :+1:
Starting with small contributions at the moment but hoping to work up to resolving more substantial issues in the future!

**Comment by antgonza** [comment]
My guess is that it's the version of miniconda and future ... will issue a PR soon.

**Comment by antgonza** [comment]
@jenwei that's great to hear. Note that #1516 fixes the failures.

**Comment by josenavas** [comment]
@jenwei do you mind pulling from upstream/master and pushing again?

**Comment by jenwei** [comment]
@josenavas just pulled/merged from upstream and pushed

**Comment by josenavas** [comment]
Fixes: https://github.com/biocore/qiita/issues/1511

:+1: 

@mortonjt wanna review/merge? Should take a couple of seconds :smile:

**Comment by mortonjt** [comment]
:+1:

**Pull request merged**
