### PR TITLE
adds EBI submission of shotgun samples

### PR DESCRIPTION
**Pull request by antgonza**
This is still being tested in our test environment but in theory these are all the required changes. 

Now, I think this should go to the release candidate but for some reason, if I try to do the PR against that branch it raises a bunch of conflicts ... any ideas?

### CODE REVIEW

**Comment by antgonza** [comment]
The submission is finally done and was successful. This is ready to go. Now, my guess is that this should be moved to the release-candidate branch, right? 

BTW the submission is still not in the main qiita, I'll start moving files now. Once the code and the files are in place I'll resubmit from the main qiita so we can have a full submission.

**Comment by josenavas** [comment]
Yes - can you do the PR against release-candidate?

**Comment by antgonza** [comment]
Is that good enough?

**Comment by antgonza** [comment]
Done.

**Pull request merged**
