### PR TITLE
DO NOT MERGE: Adding database layout for Single Strain WGS

### PR DESCRIPTION
**Pull request by josenavas**
@RNAer can you check if I missed something?

@biocore/qiita-dev This is the base db layout for the Single Strain WGS. As you'll seem, it is not affecting any part of the code so the tests should pass.

With this in master, @RNAer, me and whoever wants to work on this section will be able to add all the needed bits to add this pipeline to Qiita. Once this is merged, I will create a branch on upstream and a dummy PR with a list of all the things that need to be added for this pipeline to be in place.

As you know, DB changes conflicts are hard to resolve, and there is a fair amount of work on re-doing this PR (not hard, but really time consuming). so I will appreciate fast reviews on this.

Thanks!

### CODE REVIEW

**Comment by RNAer** [comment]
:+1:

**Comment by josenavas** [comment]
This is ready for review/merge.

**Comment by antgonza** [comment]
We should discuss this in the next meeting, some points to consider:
- Should we create a new schema for these?
- Should we create a new DB for these?
- What about making these tables/code a plug in for qiita?

**Comment by josenavas** [comment]
Open to discussion. Just want to highlight that the tables are not fully independent of the rest of the system, they are using some tables that are already present on the system (e.g. sample, prep template, raw_data, and PreprocessedData).

This means that new schema or new DB are not possible because it will not allow the ability of FK to these tables.

Re: plug in. If this becomes a plugin, I would suggest that any pipeline should be a plugin. This starts smelling to QIIME 2, so we should be careful with this.

**Comment by antgonza** [comment]
Cool, let's talk about it ... the idea of start working in QIIME 2 "smells" great!

**Comment by mortonjt** [comment]
Noticed that this hasn't been touched for a while.  What is needed for this?

**Comment by josenavas** [comment]
This no longer applies - it can be closed - This needs to be completely reworked and done as a plugin. The main blocker for this project is micronota.

**Pull request closed without merging**
