### PR TITLE
Update patch 22

### PR DESCRIPTION
**Pull request by squirrelo**
This adds deletion of duplicate selections in the analysis_sample table before adding the PK

### CODE REVIEW

**Comment by squirrelo** [comment]
Ready for review

**Comment by antgonza** [comment]
I thought we agreed we will just erase those duplicated rows. If so, I do not understand why we need to create a copy of the full table, could you comment?

**Comment by squirrelo** [comment]
Since there is no current key or way to differentiate rows, you need to create that copy with the counter as an added row. Then you delete all and reinsert the rows with just one copy (the rn = 1).

**Comment by antgonza** [comment]
:+1:

**Comment by adamrp** [comment]
looks good to me, but I'll wait until tests pass :+1:

**Pull request merged**
