### PR TITLE
Reorganize click commands

### PR DESCRIPTION
**Pull request by adamrp**
See #913

### CODE REVIEW

**Comment by josenavas** [comment]
Thanks for working on this @adamrp I commented late on the issue. Is it possible to change to qiita-admin if other people agree?

**Comment by adamrp** [comment]
I was wondering about whether or not to do that, and I decided against it, but would like to hear others' opinions. The reason I didn't make the change is that *all* of the CLI commands assume admin access, so it seemed a little weird to me to have an explicit `qiita-admin` script -- after all, many of the commands in the regular `qiita` script are largely administrative (`qiita maintenance` commands, `qiita pet webserver` command(s), etc.)

**Comment by adamrp** [comment]
Note that the original reason for having these two scripts was out of necessity -- the commands that created/destroyed the environment (`qiita_env`) couldn't be in the same file as the commands that manipulated an existing environment (`qiita`) because many of the default arguments to parameters in the `qiita` script assume an existing environment. So, the `qiita_env` script really was (at least originally) intended to get around that problem

**Comment by josenavas** [comment]
That's a really good point @adamrp :+1: on leaving as it is.

**Comment by adamrp** [comment]
This should be good to go -- tests pass, and coverage remained the same (not sure why the github interface isn't being populated with the coveralls results...)

**Comment by antgonza** [comment]
Could you also change the md files to reflect these changes?

**Comment by adamrp** [comment]
Good catch @antgonza! I think I caught all occurrences.

**Comment by antgonza** [comment]
:+1:

**Comment by ElDeveloper** [comment]
Can you add a mention to the changelog?

Yoshiki Vázquez-Baeza

**Comment by adamrp** [comment]
Good idea, @ElDeveloper, thanks. Added.

**Comment by adamrp** [comment]
Still not sure what's up with coveralls here, but this is ready for another round of review

**Comment by ElDeveloper** [comment]
> Is it possible to change to qiita-admin if other people agree?

:+1: I like that better than `qiita-env`, `env` makes a lot of sense to us because that's the term we've been using to refer to our development environments, but it doesn't make sense when put in the context of a production server (I think).

**Comment by adamrp** [comment]
@ElDeveloper currently the commands in `qiita-env` are:
```
Commands:
  clean_test     Cleans the test database environment.
  drop           Drops the database specified in config
  job_details    Pretty print moi job details
  make           Creates the database specified in config
  patch          Patches the database schema based on the...
  start_cluster  Start a compute environment
  stop_cluster   Stop a compute environment
  test           Test the environment Check to make sure that...
```
All of which are indeed related to the environment. `qiita-admin` doesn't make more sense to me than `qiita-env` for this reason, as well as the other reasons I mentioned in my previous comments. So far it's 2 :+1:s for keeping it the same, and 1 :-1: for changing to `qiita-admin`. Any other votes?

**Comment by ElDeveloper** [comment]
` ¯\_(ツ)_/¯`

**Comment by adamrp** [comment]
Any further comments on this?

**Comment by antgonza** [comment]
:+1:

**Pull request merged**
