### PR TITLE
MAINT: update required skbio version

### PR DESCRIPTION
**Pull request by gregcaporaso**
Issuing a PR to see if Qiita can work with the most recent skbio release, and to reduce the stringency of the scikit-bio version requirement as we're guaranteeing backward compatibility in the 0.2.x branch. 

Definitely let the tests complete on this one.

### CODE REVIEW

**Comment by antgonza** [comment]
@gregcaporaso flake8 errors.

**Comment by gregcaporaso** [comment]
That last commit should take care of it, thanks!

**Comment by gregcaporaso** [comment]
@antgonza, looks like we're good now.

**Comment by antgonza** [comment]
Yup! :+1: Just note that in qiita we need two reviewers to merge.

**Comment by gregcaporaso** [comment]
Ok, thanks!

**Comment by josenavas** [comment]
Thanks @gregcaporaso

**Pull request merged**
