### PR TITLE
Fix sample obj

### PR DESCRIPTION
**Pull request by josenavas**
This PR is build on top of ~~#1072~~ (merged) and #1073. At least #1072 should be merged in master before merging this one, so the commits from there (quite a few) disappear here.

This PR fixes the BaseSample, Sample and PrepSample objects and their tests. The tests for these objects are expected to pass.

### CODE REVIEW

**Comment by squirrelo** [comment]
#1073 was just merged, can you pull upstream on this?

**Comment by josenavas** [comment]
@squirrelo Done!

**Comment by squirrelo** [comment]
:+1:

**Comment by adamrp** [comment]
Looks good. @squirrelo @josenavas is there a way to test this, or are we merging everything into the `relax-md-req` first, and saving the testing for later?

**Comment by josenavas** [comment]
@adamrp all the functionality is not in place after a couple more PR. I think the best path is to review the code to see if there is anything horribly wrong, and then wait for the PR that everything is in place to make sure that everything is correct. Is really hard to test until everything is in place, but if the code looks good, I can fix the remaining issues later. Does everybody agrees with that?

**Comment by ElDeveloper** [comment]
@josenavas, yes that's a good strategy moving forward.

**Comment by adamrp** [comment]
great! Thanks.

**Pull request merged**
