### PR TITLE
MAINT: Change email from mcdonadt->qiita.help

### PR DESCRIPTION
**Pull request by ElDeveloper**

### CODE REVIEW

**Comment by antgonza** [comment]
:+1: if tests pass ....

**Comment by ElDeveloper** [comment]
:L

**Comment by josenavas** [comment]
:+1: good to merge after tests pass

**Comment by josenavas** [comment]
Just for the record: fixes https://github.com/biocore/qiita/issues/1454

**Comment by ElDeveloper** [comment]
Good point!

**Pull request merged**
