### PR TITLE
Updates jobs to add distance matrix files

### PR DESCRIPTION
**Pull request by JWDebelius**
Fixes issue #16 ?

### CODE REVIEW

**Comment by JWDebelius** [comment]
The support files for testing need to be added to the populate_test_db.sql. @squirrelo, @josenavas: can you help, please?

**Comment by ElDeveloper** [comment]
:+1:, can we add a python patch to retrieve the currently existing distance matrices?

**Comment by ElDeveloper** [comment]
Thanks for the explanation @antgonza and @JWDebelius.

**Comment by ElDeveloper** [comment]
:+1:

**Comment by ElDeveloper** [comment]
@JWDebelius, this looks fine, except for the fact that when you click on the name of the distance matrix, you get the data displayed in the iframe, instead of it being downloaded to your computer (which is what I was expecting and what I think we need this to do).

**Comment by ElDeveloper** [comment]
http://stackoverflow.com/a/18678698/379593

**Comment by wasade** [comment]
Distance matrices can get very large, will these be going through nginx for
the nom-tornado download? Might be useful to compress too

**Comment by ElDeveloper** [comment]
@wasade, to answer your question as per @adamrp's description: yes it will go through nginx. As for compression, this would be something that we need to fix in the processing pipeline, not necessarily in the display.

**Comment by wasade** [comment]
Great, thanks!

**Comment by JWDebelius** [comment]
@squirrelo: Not sure how to do nginx or tornado, can you take over.

**Comment by ElDeveloper** [comment]
@JWDebelius, note that you don't have to make any nginx/tornado changes,
just make it such that when clicking the link a file is downloaded
instead of displayed in the user interface.

**Comment by josenavas** [comment]
@JWDebelius ETA on this PR? re: download check how the links are created for downloading the sample template and you'll have an example.

**Comment by JWDebelius** [comment]
This is a problem of being able to download a file, or a display a file,
depending on the file. Each behavior is trivial to replicate, given the
codebase. However, the logic behind piping the figures is non-trivial.

**Comment by ElDeveloper** [comment]
@JWDebelius Let me know if you need help figuring this out.

**Pull request closed without merging**
