### PR TITLE
fix #995

### LINKED ISSUE #995: Another random test failure
```
======================================================================
FAIL: test_categories (qiita_db.test.test_metadata_template.DecoratedClass)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/biocore/qiita/qiita_db/test/test_metadata_template.py", line 1311, in test_categories
    self.assertEqual(obs, exp)
AssertionError: Items in the second set but not the first:
'longitude'
```
Not sure why this is happening, but very rarely it will just fail to find that column in tests.

### PR DESCRIPTION
**Pull request by antgonza**

### CODE REVIEW

**Comment by ElDeveloper** [comment]
Should we have the tests run a few times to see if we can get the
"stochastic" failure to reproduce?

**Comment by antgonza** [comment]
yup

**Comment by antgonza** [comment]
Just started 2nd pass, how many should we do? 4?

**Comment by squirrelo** [comment]
We did 5 for the last one, so I'd say 5 is sufficient.

**Comment by antgonza** [comment]
Current failure is due to timeout, gonna run again.
```
======================================================================
FAIL: test_post (qiita_pet.test.test_auth_handlers.TestAuthCreateHandler)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/biocore/qiita/qiita_pet/test/test_auth_handlers.py", line 17, in test_post
    response = self.post('/auth/create/', post_args)
  File "/home/travis/build/biocore/qiita/qiita_pet/test/tornado_test_base.py", line 58, in post
    return self._fetch(url, 'POST', data, headers)
  File "/home/travis/build/biocore/qiita/qiita_pet/test/tornado_test_base.py", line 63, in _fetch
    return self.wait()
  File "/home/travis/miniconda3/envs/env_name/lib/python2.7/site-packages/tornado/testing.py", line 269, in wait
    self.__rethrow()
  File "/home/travis/miniconda3/envs/env_name/lib/python2.7/site-packages/tornado/testing.py", line 205, in __rethrow
    raise_exc_info(failure)
  File "/home/travis/miniconda3/envs/env_name/lib/python2.7/site-packages/tornado/testing.py", line 253, in timeout_func
    timeout)
AssertionError: Async operation timed out after 5 seconds
-------------------- >> begin captured logging << --------------------
tornado.access: INFO: 302 POST /auth/create/ (127.0.0.1) 1445.71ms
--------------------- >> end captured logging << ---------------------
```

**Comment by antgonza** [comment]
3rd running.

**Comment by antgonza** [comment]
Again, timeout. Rerunning.

**Comment by antgonza** [comment]
4th.

**Comment by antgonza** [comment]
5th!!!!!!

**Comment by josenavas** [comment]
I'm still surprised that this change fixes the stochastic failure... but I guess I should give my :+1: given that 5 times the tests pass...

**Comment by squirrelo** [comment]
Also confused, but it apparently fixes, so merging.

**Comment by adamrp** [comment]
Yeah, that this worked doesn't make sense to me, and I think the original
issue is probably still an issue (albeit a "sasquatch" issue). Let's keep
our eyes peeled, I also saw that issue present at the UCSD qiita sprint.

**Pull request merged**
