### PR TITLE
BUG: Fix bug in moi.init

### PR DESCRIPTION
**Pull request by ElDeveloper**
The position of the group_id argument was moved and the rest of the code
was not updated to reflect this. This change set moves group_id so it is
the first argument.

### CODE REVIEW

**Comment by ElDeveloper** [comment]
This problem would cause the analysis waiting page to be blank.

**Comment by wasade** [comment]
I'd say to open a PR upstream, but I know your take on moi...

**Comment by ElDeveloper** [comment]
@wasade, I went over there first, but I saw this: https://github.com/biocore/mustached-octo-ironman/pull/19/files ... I've added a note in the code :beer:

**Comment by ElDeveloper** [comment]
Tests are passing but it seems like coveralls has choked, anyone wants to have a look? This is blocking for the release.

**Pull request merged**
