### PR TITLE
ENH: Bring email validation closer to specs

### LINKED ISSUE #1179: Email validation is too strict
Just saw this error on the server (actual email censored, but it contains undrescores):
```
Traceback (most recent call last):

  File "/home/qiita/.virtualenvs/qiita/lib/python2.7/site-packages/tornado/web.py", line 1141, in _when_complete
    callback()

  File "/home/qiita/.virtualenvs/qiita/lib/python2.7/site-packages/tornado/web.py", line 1162, in _execute_method
    self._when_complete(method(*self.path_args, **self.path_kwargs),

  File "/home/qiita/qiita_main/qiita_pet/handlers/auth_handlers.py", line 39, in post
    created = User.create(username, password, info)

  File "/home/qiita/qiita_main/qiita_db/user.py", line 196, in create
    raise IncorrectEmailError("Bad email given: %s" % email)

IncorrectEmailError: Bad email given: email_with_underscores@hotmail.com
```
This is because of [`User.validate_email`](https://github.com/biocore/qiita/blob/master/qiita_db/user.py#L459-L487), which disallows underscores, even though they should be allowed.

Additionally, line 487
```python
return True if match(pattern, email) is not None else False
```
can be simplified to
```python
return match(pattern, email) is not None
```

### PR DESCRIPTION
**Pull request by adamrp**
Fix #1179

This doesn't fully account for all valid email addresses (doing so is too
much of a headache to implement, at least until it becomes necessary...), but
it's closer, and will pass for the majority of email addresses.

### CODE REVIEW

**Comment by wasade** [comment]
test failures, I think :+1: otherwise tho

**Comment by adamrp** [comment]
I think the only failures are the same two that are popping up on all our PRs since pandas was updated. I have a PR in for one of them #1182, but not sure about the other one :frowning:

**Comment by squirrelo** [comment]
:+1:  once the failures are worked out

**Comment by adamrp** [comment]
Merge?

**Pull request merged**
