### PR TITLE
Issue 855 patch

### PR DESCRIPTION
**Pull request by josenavas**
Adds the status attribute to the processed data object. Is the first step to start solving #855

### CODE REVIEW

**Comment by ElDeveloper** [comment]
@josenavas, there's a legitimate flake8 failure.

**Comment by josenavas** [comment]
Thanks for the heads up @ElDeveloper !

I was testing the code directly in SQL and I did not execute the patch... Now it should be working and ready for review/merge!

**Comment by josenavas** [comment]
After discussing with @antgonza looks like the best approach is to remove the study status from the db, and the property value will be inferred from the processed data contained in such study.

Given that the changes required due to the removal, it will be easier to close this PR and perform all the changes at once, rather than first introduce the patch and then modify the code.

**Comment by ElDeveloper** [comment]
Thanks!

**Pull request closed without merging**
