### PR TITLE
Fixing minimal mapping generation

### LINKED ISSUE #1475: Unlinked files due to error, can't re-link them.
I have two sequencing files (forward and reverse reads) and a barcode file for each (Study #10297). I attempted to link them, but only selected one barcode file. I got the following error: 

*Status: failed: Job PREPROCESS: Error Job results: ValueError(Failed to execute: split_libraries_fastq.py --store_demultiplexed_fastq -i /projects/qiita_data/raw_data/700_April2015V4_S1_L001_R1_001.fastq -b /projects/qiita_data/raw_data/700_barcode_April1.txt -m /projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_001_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_002_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_003_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_004_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_005_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_006_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_007_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_008_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_009_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_010_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_011_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_012_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_013_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_014_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_015_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_016_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_017_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_018_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_019_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_020_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_021_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_022_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_023_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_024_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_025_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_026_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_027_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_028_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_029_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_030_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_031_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_032_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_033_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_034_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_035_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_036_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_037_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_038_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_039_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_040_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_041_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_042_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_043_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_044_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_045_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_046_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_047_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_048_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_049_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_050_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_051_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_052_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_053_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_054_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_055_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_056_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_057_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_058_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_059_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_060_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_061_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_062_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_063_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_064_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_065_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_066_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_067_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_068_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_069_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_070_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_071_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_072_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_073_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_074_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_075_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_076_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_077_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_078_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_079_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_080_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_081_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_082_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_083_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_084_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_085_MMF.txt -o /projects/qiita_data/working_dir/slq_out_1031_700_Aqrkm1 --barcode_type 8 --max_bad_run_length 3 --max_barcode_errors 1.5 --min_per_read_length_fraction 0.75 --phred_quality_threshold 3 --sequence_max_n 0 stdout: stderr: Usage: split_libraries_fastq.py [options] {-i/--sequence_read_fps SEQUENCE_READ_FPS -o/--output_dir OUTPUT_DIR} [] indicates optional input (order unimportant) {} indicates required input (order unimportant) Example usage: Print help message and exit split_libraries_fastq.py -h Demultiplex and quality filter (at Phred >= Q20) one lane of Illumina fastq data and write results to ./slout_q20.: split_libraries_fastq.py -i lane1_read1.fastq.gz -b lane1_barcode.fastq.gz --rev_comp_mapping_barcodes -o slout_q20/ -m map.txt -q 19 Demultiplex and quality filter (at Phred >= Q20) one lane of Illumina fastq data and write results to ./slout_q20. Store trimmed quality scores in addition to sequence data.: split_libraries_fastq.py -i lane1_read1.fastq.gz -b lane1_barcode.fastq.gz --rev_comp_mapping_barcodes -o slout_q20/ -m map.txt --store_qual_scores -q 19 Demultiplex and quality filter (at Phred >= Q20) two lanes of Illumina fastq data and write results to ./slout_q20.: split_libraries_fastq.py -i lane1_read1.fastq.gz,lane2_read1.fastq.gz -b lane1_barcode.fastq.gz,lane2_barcode.fastq.gz --rev_comp_mapping_barcodes -o slout_q20/ -m map.txt,map.txt --store_qual_scores -q 19 Quality filter (at Phred >= Q20) one non-multiplexed lane of Illumina fastq data and write results to ./slout_single_sample_q20.: split_libraries_fastq.py -i lane1_read1.fastq.gz --sample_id my.sample.1 -o slout_single_sample_q20/ -q 19 --barcode_type 'not-barcoded' Quality filter (at Phred >= Q20) two non-multiplexed lanes of Illumina fastq data with different samples in each and write results to ./slout_not_multiplexed_q20.: split_libraries_fastq.py -i lane1_read1.fastq.gz,lane2_read1.fastq.gz --sample_id my.sample.1,my.sample.2 -o slout_not_multiplexed_q20/ -q 19 --barcode_type 'not-barcoded' split_libraries_fastq.py: error: Same number of sequence, barcode, and mapping files must be provided. ) Python output: None Standard output: Standard error: Job GEN_DEMUX_FILE: Error Job results: ImpossibleDependency() Python output: None Standard output: Standard error: Job INSERT_PREPROCESSED: Error Job results: ImpossibleDependency() Python output: None Standard output: Standard error:*

Oops. Looks like I need to link both barcode files? I unlinked all the files and when I went to re-link them the normal drop-down menus where I designate what type of file each file is were missing. Here's a picture:

screen grab

I'm not sure how to proceed.

Thanks,

Zac

### PR DESCRIPTION
**Pull request by josenavas**
Fixes #1475 

The issue is that we were parsing the QIIME mapping file and pandas was inferring the sample ids as numbers, removing trailing zeros. Here, I generate the minimal mapping file from the information on the database, so no parsing is done.

It should be quick to review and its priority is high, as it is blocking some users to process their data.

### CODE REVIEW

**Comment by wasade** [comment]
:+1:

**Comment by antgonza** [comment]
Is there a way to add test for these changes?

**Comment by josenavas** [comment]
good point, will do soon

**Comment by mortonjt** [comment]
This is a side note.  Just looking at the code, there a few objects (i.e. `PrepTemplate`) that aren't imported, but are passed in as parameters.  So it isn't clear exactly where these object definitions are.

Would it be worthwhile to update the documentation for these parameters?  I'd be willing to submit a separate PR to do this if you guys think it is a good idea.

**Comment by josenavas** [comment]
what is your proposed solution to update the documentation?

**Comment by mortonjt** [comment]
I was thinking something instead of 
```
PrepTemplate
```
do
```
qiita_db.metadata_template.PrepTemplate
```
We can probably work out the abbreviations if we'd like.

**Comment by josenavas** [comment]
Ok, that has not been a standard way of doing things in qiita. We can change, but I would like to hear from other devs:

@antgonza @ElDeveloper @wasade what do you think on start using such nomenclature?

**Comment by wasade** [comment]
There is precedent in [skbio](https://github.com/biocore/scikit-bio/blob/master/skbio/alignment/_alignment.py#L32), but I don't have strong feelings on this.

**Comment by mortonjt** [comment]
idk,  it may make it easier to contribute.  Otherwise, I find myself periodically running through dumps from 
```
grep -rnw . -e 'PrepTemplate'
```

**Comment by josenavas** [comment]
Sounds good - will change in this function - and we can slowly transition the rest of the code (there is plenty of instances in the code...)

**Comment by josenavas** [comment]
Comments addressed @mortonjt and @antgonza

**Comment by antgonza** [comment]
Thanks but you are missing a test for the reversebarcode option, right?

**Comment by josenavas** [comment]
There is already a bunch of other tests for that function. The only test that we're missing is one using numeric sample ids, which is the bug that we found.

**Comment by antgonza** [comment]
K, as we already had a :+1: and I can see that the issues were solved, I'm gonna merge.

**Pull request merged**
