### PR TITLE
improved error handling when attempting to preprocess a fasta without qual

### PR DESCRIPTION
**Pull request by gregcaporaso**
this partially addresses #953

### CODE REVIEW

**Comment by ElDeveloper** [comment]
I would like to bring this to the attention of the rest of the @biocore/qiita-dev group. The problem is that the minimum quality value gets added to the `split_libraries.py` command even though you would be processing a study with no quality FASTA files. So the solution is to add a new entry to the database with parameters for sequences with no quality.

If I'm underestimating the problem and this is a bigger issue, this PR does a great job at ameliorating the current situation for the time being, so :+1: .

**Comment by antgonza** [comment]
IMOO this is fine as it makes it clearer in the DB that is another
kind of preprocessing: no quality checking.

**Comment by wasade** [comment]
This sounds good

**Comment by ElDeveloper** [comment]
:+1:

**Comment by josenavas** [comment]
I discussed this with @gregcaporaso and I agree with @antgonza: it is either a new kind of preprocessing (no quality checking) or we need to do quite a few modifications to the database/code base to support that.

**Pull request merged**
