### PR TITLE
Allow hypens, but not at beginning or end

### LINKED ISSUE #1232: valid email not being accepted
A user reported not being able to create an account and only getting a 500 error. 

After checking the logs (note that I'm replacing the actual email for: name@a.b-c.d, which is the general format of the original email):
ERROR:
Bad email given: name@a.b-c.d
TRACE:
Traceback (most recent call last):

File "/home/qiita/.virtualenvs/qiita/lib/python2.7/site-packages/tornado/web.py", line 1141, in _when_complete
callback()

File "/home/qiita/.virtualenvs/qiita/lib/python2.7/site-packages/tornado/web.py", line 1162, in _execute_method
self._when_complete(method(*self.path_args, **self.path_kwargs),

File "/home/qiita/qiita_main/qiita_pet/handlers/auth_handlers.py", line 39, in post
created = User.create(username, password, info)

File "/home/qiita/qiita_main/qiita_db/user.py", line 196, in create
raise IncorrectEmailError("Bad email given: %s" % email)

IncorrectEmailError: Bad email given: name@a.b-c.d

### PR DESCRIPTION
**Pull request by adamrp**
Fix #1232

### CODE REVIEW

**Comment by antgonza** [comment]
:+1: if tests pass

**Comment by josenavas** [comment]
:+1: 

I'm really surprised that we are having so many issues checking emails... This is something that is constantly done in the intertubes and I don't think people has that many problems.

Probably we shouldn't be restrictive at all (just check that it looks like <something>@<something>.<something>). If the user provides a bad email he will never be able to use the system. We can then remove the emails that have not been validated for more than 2 weeks...

**Comment by adamrp** [comment]
The regex for identifying valid email addresses is [surprisingly complex](http://www.regular-expressions.info/email.html) and adherence to the standards varies. I am not against relaxing the checking, but I'd be surprised if we continue to see more false negatives here.

**Comment by josenavas** [comment]
Thanks for the link @adamrp! I think now it makes more sense why it is so complex...

**Pull request merged**
